[project]
name = "gateway"
version = "0.0.1"
description = "API Gateway for SOVA RAG Platform"
requires-python = "==3.14.4"


dependencies = [
    "fastapi>=0.141.1",
    "shared",
]

[tool.uv.sources]
shared = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["gateway"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
